# AutoEncoder

In [2]:
import numpy as np
import pandas as pd
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, Input
from sklearn.datasets import load_iris

In [3]:
data = load_iris().data

In [12]:
input_layer = Input(shape=(4,))

encode_layer1 = Dense(8,activation='relu')(input_layer)
encode_layer2 = Dense(16,activation='relu')(encode_layer1)

middle_layer = Dense(8,activation='relu')(encode_layer2)

decode_layer1 = Dense(16,activation='relu')(middle_layer)
decode_layer2 = Dense(8,activation='relu')(decode_layer1)

output_layer = Dense(4,activation='linear')(decode_layer2)

In [13]:
auto_encoder = Model(input_layer,output_layer)

In [14]:
auto_encoder.compile(optimizer='adam', loss='mse', metrics=['mae'])

In [15]:
auto_encoder.fit(data,data, epochs=300,batch_size=40)

Epoch 1/300
150/150 [==============================] - 0s 2ms/sample - loss: 15.8281 - mean_absolute_error: 3.4683
Epoch 2/300
150/150 [==============================] - 0s 203us/sample - loss: 15.6936 - mean_absolute_error: 3.4501
Epoch 3/300
150/150 [==============================] - 0s 175us/sample - loss: 15.5695 - mean_absolute_error: 3.4345
Epoch 4/300
150/150 [==============================] - 0s 181us/sample - loss: 15.4246 - mean_absolute_error: 3.4158
Epoch 5/300
150/150 [==============================] - 0s 161us/sample - loss: 15.2291 - mean_absolute_error: 3.3830
Epoch 6/300
150/150 [==============================] - 0s 206us/sample - loss: 14.9911 - mean_absolute_error: 3.3393
Epoch 7/300
150/150 [==============================] - 0s 209us/sample - loss: 14.6846 - mean_absolute_error: 3.2847
Epoch 8/300
150/150 [==============================] - 0s 247us/sample - loss: 14.3047 - mean_absolute_error: 3.2176
Epoch 9/300
150/150 [==============================] - 0s 214us/sa

Epoch 71/300
150/150 [==============================] - 0s 158us/sample - loss: 0.4875 - mean_absolute_error: 0.5179
Epoch 72/300
150/150 [==============================] - 0s 150us/sample - loss: 0.4796 - mean_absolute_error: 0.5156
Epoch 73/300
150/150 [==============================] - 0s 148us/sample - loss: 0.4709 - mean_absolute_error: 0.5104
Epoch 74/300
150/150 [==============================] - 0s 145us/sample - loss: 0.4616 - mean_absolute_error: 0.5044
Epoch 75/300
150/150 [==============================] - 0s 141us/sample - loss: 0.4511 - mean_absolute_error: 0.4986
Epoch 76/300
150/150 [==============================] - 0s 143us/sample - loss: 0.4408 - mean_absolute_error: 0.4924
Epoch 77/300
150/150 [==============================] - 0s 148us/sample - loss: 0.4297 - mean_absolute_error: 0.4852
Epoch 78/300
150/150 [==============================] - 0s 163us/sample - loss: 0.4175 - mean_absolute_error: 0.4775
Epoch 79/300
150/150 [==============================] - 0s 151us

150/150 [==============================] - 0s 152us/sample - loss: 0.0287 - mean_absolute_error: 0.1294
Epoch 210/300
150/150 [==============================] - 0s 146us/sample - loss: 0.0286 - mean_absolute_error: 0.1291
Epoch 211/300
150/150 [==============================] - 0s 147us/sample - loss: 0.0286 - mean_absolute_error: 0.1288
Epoch 212/300
150/150 [==============================] - 0s 147us/sample - loss: 0.0285 - mean_absolute_error: 0.1284
Epoch 213/300
150/150 [==============================] - 0s 154us/sample - loss: 0.0284 - mean_absolute_error: 0.1283
Epoch 214/300
150/150 [==============================] - 0s 154us/sample - loss: 0.0283 - mean_absolute_error: 0.1280
Epoch 215/300
150/150 [==============================] - 0s 148us/sample - loss: 0.0283 - mean_absolute_error: 0.1278
Epoch 216/300
150/150 [==============================] - 0s 133us/sample - loss: 0.0282 - mean_absolute_error: 0.1275
Epoch 217/300
150/150 [==============================] - 0s 155us/samp

In [17]:
data[0]

array([5.1, 3.5, 1.4, 0.2])

In [18]:
auto_encoder.predict(data[0].reshape(-1,4))

array([[5.0724773 , 3.5076873 , 1.3994441 , 0.20566149]], dtype=float32)

In [19]:
encoder = Model(input_layer,middle_layer)

In [22]:
encrypted_data = encoder.predict(data[0].reshape(-1,4))

In [23]:
encoder.summary()

Model: "model_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 4)]               0         
_________________________________________________________________
dense_6 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_7 (Dense)              (None, 16)                144       
_________________________________________________________________
dense_8 (Dense)              (None, 8)                 136       
Total params: 320
Trainable params: 320
Non-trainable params: 0
_________________________________________________________________


In [25]:
decoder_input = Input(shape=(8,))
decoder_layer11 = auto_encoder.layers[4](decoder_input)
decoder_layer12 = auto_encoder.layers[5](decoder_layer11)
output_layer1 = auto_encoder.layers[6](decoder_layer12)

decoder = Model(decoder_input, output_layer1)

In [26]:
decoder.predict(encrypted_data)

array([[5.0724773 , 3.5076873 , 1.3994441 , 0.20566149]], dtype=float32)

Dinemsion reduction using ANN (Do yourself)

# Convolutional Neural Network

In [27]:
from tensorflow.keras.layers import Conv2D, MaxPool2D, Flatten, Dense

In [28]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.datasets import cifar10
import matplotlib.pyplot as plt

In [29]:
(x_train,y_train),(x_test,y_test) = cifar10.load_data()

170500096/170498071 [==============================] - 295s 2us/step


In [30]:
from tensorflow.keras.utils import to_categorical

In [31]:
y_train = to_categorical(y_train)

In [33]:
model = Sequential()

model.add(Conv2D(input_shape=(32,32,3),kernel_size=(3,3),filters=4))
model.add(MaxPool2D(pool_size=(2,2)))
model.add(Conv2D(kernel_size=(2,2),filters=4))
model.add(MaxPool2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(256,activation='relu'))
model.add(Dense(128,activation='relu'))
model.add(Dense(64,activation='relu'))
model.add(Dense(32,activation='relu'))
model.add(Dense(16,activation='relu'))
model.add(Dense(10,activation='softmax'))

model.compile(optimizer='adam', loss='categorical_crossentropy',metrics=['accuracy'])

In [34]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 30, 30, 4)         112       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 15, 15, 4)         0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 14, 14, 4)         68        
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 7, 7, 4)           0         
_________________________________________________________________
flatten (Flatten)            (None, 196)               0         
_________________________________________________________________
dense_12 (Dense)             (None, 256)               50432     
_________________________________________________________________
dense_13 (Dense)             (None, 128)              

In [ ]:
model.fit(x_train,y_train,epochs=100,batch_size=32)